stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.6.3-openjdk-11
      shellScript: mvn package -DskipTests -Djava.util.logging.config.file=vertx-default-jul-logging.properties
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-data-import-converter-storage:spitfire-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-htqfq:spitfire-helmcharts-mod-data-import-converter-storage
      version: 0.1.32
      answers:
        image.repository: docker.dev.folio.org/mod-data-import-converter-storage
        image.tag: spitfire-${CICD_EXECUTION_SEQUENCE}
      targetNamespace: spitfire
      name: mod-data-import-converter-storage
timeout: 60
notification: {}
