#%RAML 1.0

title: Data Import Converter Storage
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Data Import Converter Storage API
    content: API for managing data import profiles

types:
  errors: !include raml-storage/raml-util/schemas/errors.schema
  jobProfile: !include raml-storage/schemas/mod-data-import-converter-storage/jobProfile.json
  jobProfileCollection: !include raml-storage/schemas/mod-data-import-converter-storage/jobProfileCollection.json
  matchProfile: !include raml-storage/schemas/mod-data-import-converter-storage/matchProfile.json
  matchProfileCollection: !include raml-storage/schemas/mod-data-import-converter-storage/matchProfileCollection.json
  actionProfile: !include raml-storage/schemas/mod-data-import-converter-storage/actionProfile.json
  actionProfileCollection: !include raml-storage/schemas/mod-data-import-converter-storage/actionProfileCollection.json

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml
  language: !include raml-storage/raml-util/traits/language.raml
  pageable:  !include raml-storage/raml-util/traits/pageable.raml
  searchable: !include raml-storage/raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-storage/raml-util/rtypes/collection.raml
  collection-item: !include raml-storage/raml-util/rtypes/item-collection.raml

/data-import-profiles:
  /jobProfiles:
    displayName: Job Profiles
    description: API for managing Job Profiles
    type:
      collection:
        schemaCollection: jobProfileCollection
        schemaItem: jobProfile
        exampleCollection: !include raml-storage/examples/mod-data-import-converter-storage/jobProfileCollection.sample
        exampleItem: !include raml-storage/examples/mod-data-import-converter-storage/jobProfile.sample
    post:
      is: [validate]
    get:
      is: [
        searchable: {description: "with valid searchable fields: for example userInfo.lastName=Doe", example: "userInfo.lastName=Doe"},
        pageable,
        validate
      ]
    /{id}:
      displayName: Job Profile
      description: Get, Delete or Update a specific Job Profile
      type:
        collection-item:
          schema: jobProfile
          exampleItem: !include raml-storage/examples/mod-data-import-converter-storage/jobProfile.sample
      put:
        is: [validate]
        responses:
          200:
            body:
              application/json:
                type: jobProfile
      delete:
        responses:
          204:
            body:
              text/plain: !!null
  /matchProfiles:
    displayName: Match Profiles
    description: API for managing Match Profiles
    type:
      collection:
        schemaCollection: matchProfileCollection
        schemaItem: matchProfile
        exampleCollection: !include raml-storage/examples/mod-data-import-converter-storage/matchProfileCollection.sample
        exampleItem: !include raml-storage/examples/mod-data-import-converter-storage/matchProfile.sample
    post:
      is: [validate]
    get:
      is: [
        searchable: {description: "with valid searchable fields: for example userInfo.lastName=Doe", example: "userInfo.lastName=Doe"},
        pageable,
        validate
      ]
    /{id}:
      displayName: Match Profile
      description: Get, Delete or Update a specific Match Profile
      type:
        collection-item:
          schema: matchProfile
          exampleItem: !include raml-storage/examples/mod-data-import-converter-storage/matchProfile.sample
      put:
        is: [validate]
        responses:
          200:
            body:
              application/json:
                type: matchProfile
      delete:
        responses:
          204:
            body:
              text/plain: !!null
  /actionProfiles:
    displayName: Action Profiles
    description: API for managing Action Profiles
    type:
      collection:
        schemaCollection: actionProfileCollection
        schemaItem: actionProfile
        exampleCollection: !include raml-storage/examples/mod-data-import-converter-storage/actionProfileCollection.sample
        exampleItem: !include raml-storage/examples/mod-data-import-converter-storage/actionProfile.sample
    post:
      is: [validate]
    get:
      is: [
        searchable: {description: "with valid searchable fields: for example userInfo.lastName=Doe", example: "userInfo.lastName=Doe"},
        pageable,
        validate
      ]
    /{id}:
      displayName: Action Profile
      description: Get, Delete or Update a specific Action Profile
      type:
        collection-item:
          schema: actionProfile
          exampleItem: !include raml-storage/examples/mod-data-import-converter-storage/actionProfile.sample
      put:
        is: [validate]
        responses:
          200:
            body:
              application/json:
                type: actionProfile
      delete:
        responses:
          204:
            body:
              text/plain: !!null
